Training:
 train_size: 0.9 # 90% of the data for training and 10% for testing
 training_epochs: 80 # training steps
 batch_size: 30 # number of data to use in each epoch
 display_step: 5
 learning_rate: 0.001
 regularizer_rate: 0.1
 dropout_prob: 0.6

Architecture:
 hidden_layers: 2 # number of hidden layers
 neuron_hidden: 80 # number of neurons in each hidden layer



