Training:
 train_size: 0.9 # % of the data for training, the rest is testing
 validation_size: 0.2 # % To validate 
 epochs: 10
 random_state: 1
 learning_rate: 0.001
 regularization: False
 regularizer_rate: 0.001
 dropout_prob: 0.6
 
TrainingKfold:
 train_size: 0.95 # % of the data for training, the rest is testing
 n_splits: 5 # 
 n_repeats: 5 # 
 epochs: 150
 random_state: 1 #
 

Architecture:
 hidden_layers: 5 # number of hidden layers
 neuron_hidden: 100 # number of neurons in each hidden layer
 regularizer_value: 0.0005


