Training:
 train_size: 0.75 # % of the data for training, the rest is testing
 n_splits: 5 # 
 n_repeats: 5 # 
 epochs: 200
 random_state: 1 #
 learning_rate: 0.001
 regularization: True
 regularizer_rate: 0.1
 dropout_prob: 0.6
 

Architecture:
 hidden_layers: 2 # number of hidden layers
 neuron_hidden: 100 # number of neurons in each hidden layer
 regularizer_value: 0.001


