Training:
 train_size: 0.9 # % of the data for training, the rest is testing
 n_splits: 10 # 
 n_repeats: 3 # 
 random_state: 1 # validation size
 learning_rate: 0.001
 regularizer_rate: 0.1
 dropout_prob: 0.6

Architecture:
 hidden_layers: 4 # number of hidden layers
 neuron_hidden: 20 # number of neurons in each hidden layer
 regularizer_value: 0.001


