Training:
 train_size: 0.75 # % of the data for training, the rest is testing
 validation_size: 0.2 # % To validate 
 epochs: 900
 random_state: 1
 
 # learning rate
 learning_rate: 'variable' # value: fixed lr. 'variable'
 lr_i: 0.0001
 lr_f: 0.00001
 lr_decaysteps: 50
 lr_decayrate: 0.00005
 
 # regularization and dropout
 regularization: False
 regularizer_value: 0.0005
 
 dropout_prob: 0.6
 
 # weights 
 initializer: 1 # 1: glorot initialization, 2: random for relu
 clipnorm: 1 # Gradient clipping to avoid exploding gradients
 clipvalue: 0.5
 
TrainingKfold:
 train_size: 0.95 # % of the data for training, the rest is testing
 n_splits: 5 # 
 n_repeats: 5 # 
 epochs: 150
 random_state: 1 #
 

Architecture:
 hidden_layers: 5 # number of hidden layers
 neuron_hidden: 400 # number of neurons in each hidden layer
 


