FEASIB:
 factor_pos: 300 #multiplication of position vector for scaling
 factor_vel: 1 #multiplication of velocity vector for scaling
 factor_mass: 0.1 #multiplication of mass for scaling
 feas_ep: 20000000 #allowed error in position to be feasible
 feas_ev: 2000 #allowed error in velocity to be feasible
