FEASIB:
 factor_pos: 10 #multiplication of position vector for scaling
 factor_vel: 1 #multiplication of velocity vector for scaling
 factor_mass: 0.01 #multiplication of mass for scaling
 range_mass: !!python/tuple [-3, 2]
 range_pos: !!python/tuple [-4, 0  ]
 range_vel: !!python/tuple [-1, 1]
 feas_ep: 20000000 #allowed error in position to be feasible
 feas_ev: 2000 #allowed error in velocity to be feasible
