MBH:
 niter_total: 20
 niter_success: 10 #Number of iterations before a big jump
 niter_local: 100 #Number of iterations for the local opt. TODO: it is ignored
 jumpMagnitude: 0.005 #Magnitude of the small jump 
 tolLocal: 0.01
 tolGlobal: 0.00001
 
MBH_batch:
 nind: 10
 niter_total: 100
 niter_success: 5 #Number of iterations before a big jump
 tolLocal: 0.01
 jumpMagnitude: 0.01 #Magnitude of the small jump 
 tolGlobal: 0.00001

MBH_generateDatabase: #For only small steps
 niter_total: 3
 niter_success: 20 #Number of iterations before a big jump
 niter_local: 100 #Number of iterations for the local opt. TODO: it is ignored
 jumpMagnitude: 0.01 #Magnitude of the small jump 
 tolLocal: 0.01
 tolGlobal: 0.001
 
EA:
 ind: 10000 #individuals
 iterat: 10 #iterations
 itersuccess: 2 #max iter without improvement
 elitism: 0.01
 mutat: 0.001 #probability of mutation
 immig: 0.01 # New individuals
 penalty: 10000 # penalty if it doesnt accomplish constraints


coordS:
 maxiter: 10
 stepsize:
  - 1000
  - 0.01
  - 0.01
  - 1000
  - 0.01
  - 0.01
  - 15
  - 864000
