SimsFlan:
 date0: 
  - 15 #day
  - 6 #month
  - 2019 #year
  - 0 #hour
 Nimp: 11 #Number of impulses. Must be odd so that there is a middle point!!! 

bounds:
 v0: !!python/tuple [0., 5000.] #Relative to the planet
 v0_angle: !!python/tuple [0, 2] #times pi
 vf: !!python/tuple [0., 9000.] #Relative to the planet
 vf_angle: !!python/tuple [0, 2] #times pi
 t0: !!python/tuple [0, 1000.] #+t0 for both
 t_t: !!python/tuple [200, 900.] #convert from days to seconds
 deltav_mag: !!python/tuple [0., 1.] #magnitude
 deltav_ang: !!python/tuple [-1, 1] #times pi





    
